package:
  name: divebomb
  version: "1.0.4"

source:
  git_rev: master
  git_url: https://gitlab.oceantrack.org/anunes/divebomb

build:
  number: 0

python:
  - 2.7
  - 3.5
  - 3.6

requirements:
  build:
    - python {{ python }}
    - setuptools
    - pandas
    - numpy
    - sphinx
    - plotly
    - netcdf4
    - peakutils
    - scikit-learn
    - xarray

  run:
    - python {{ python }}
    - setuptools
    - pandas
    - numpy
    - sphinx
    - plotly
    - netcdf4
    - peakutils
    - scikit-learn
    - xarray

about:
  home: https://gitlab.oceantrack.org/anunes/divebomb
  license: GPL
  license_file: LICENSE
